{% set name = "docker-compose" %}
{% set version = 1.26.0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e836102d139aca667d6af53f0f4d942c9459ec24d6dd4f0203d74359b0fd311

build:
  number: 0
  skip: true   # [py==30 or py==31 or py==32 or py==33]
  entry_points:
    - docker-compose=compose.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - backports.shutil_get_terminal_size ==1.0.0  # [py<33]
    - backports.ssl-match-hostname <4,>=3.5  # [py<35]
    - cached-property >=1.2.0,<2
    - colorama <1,>=0.4  # [win]
    - distro >=1.5.0,<2
    - docker >=3.7.0,<5
    - dockerpty >=0.4.1,<1
    - docopt >=0.6.1,<1
    - enum34 <2,>=1.0.4  # [py<34]
    - ipaddress <2,>=1.0.16  # [py<33]
    - jsonschema >=2.5.1,<4
    - python
    - python-dotenv >=0.13.0,<1
    - pyyaml >=3.10,<6
    - requests >=2.20.0,<3
    - six >=1.3.0,<2
    - subprocess32 <4,>=3.5.4  # [py<32]
    - texttable >=0.9.0,<2
    - websocket-client >=0.32.0,<1

test:
  imports:
    - compose
    - compose.cli
  commands:
    - pip check
    - docker-compose --help
  requires:
    - pip

about:
  home: https://www.docker.com/
  summary: Multi-container orchestration for Docker
  dev_url: https://github.com/docker/compose
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scopatz
