{% set name = "iniconfig" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iniconfig-{{ version }}.tar.gz
  sha256: bc3af051d7d14b2ee5ef9969666def0cd1a000e121eaea580d4a313df4b37f32

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python

test:
  imports:
    - iniconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/RonnyPfannschmidt/iniconfig
  summary: 'iniconfig: brain-dead simple config-ini parsing'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
